// Generated by CoffeeScript 1.7.1
(function() {
  var megaParse, prop, string;

  prop = {
    title: "Shadow of the Colossus",
    developer: "Sony Japan",
    publisher: "SCEA",
    platform: "Playstation 2",
    players: 1,
    online_access: false,
    released: 2005,
    esrb_rating: "T"
  };

  megaParse = function(s) {
    var key, obj, value;
    obj = JSON.parse(s);
    console.log("Length: " + Object.keys(obj).length);
    for (key in obj) {
      value = obj[key];
      console.log("The name " + key + " has the value of " + obj[key]);
    }
    return obj;
  };

  string = JSON.stringify(prop);

  megaParse(string);

}).call(this);
